### ISSUE TITLE
[bsconfig] "stagingDir" property is not normalised to an absolute paths relative to the config file

### ISSUE THREAD

**Issue by bartvandenende-wm** [rokucommunity/brighterscript#1141]
## Summary

"stagingDir" property in `bsconfig.json` is not resolved relative to the config file

## Repro steps

given the below two config files
1. **./node_modules/shared-config/bsconfig.json**
```json
  "rootDir": "../../src",
  "stagingDir": "../../build"
```

2. **./bsconfig.json**
```json
{
  "extends": "./node_modules/shared-config/bsconfig.json",
}
```

3. results in two different path resolutions
```typescript
import {Util} from "brighterscript"
const util = new Util()
const config = util.loadConfigFile("./bsconfig.json");
console.log(`rootDir: ${config.rootDir}`)
console.log(`stagingDir: ${config.stagingDir}`)
```

 **Expected result:**
  
```terminal 
$ rootDir: {cwd-dir}/src
$ stagingDir: {cwd-dir}/build
```
 
 **Actual result:**
  
```terminal 
$ rootDir: {cwd}/src
$ stagingDir: {cwd}/../../build
```

## Details

path normalisation is missing in the `loadConfigFile` utility for the `stagingDir`
https://github.com/rokucommunity/brighterscript/blob/483a15454f1c8751619421ee4c99dbf4fdd073d7/src/util.ts#L227-L237

**Comment by josephjunker** [comment]
I wonder how much room there is for design here, if we consider breaking changes. The behavior that I would personally expect would be for the paths to be resolved relative to the child bsconfig. For example, if the desired result was

```
rootDir: {cwd}/src
stagingDir: {cwd}/build
```

then I would want `./node_modules/shared-config/bsconfig.json` to contain this:

```
rootDir: "./src",
stagingDir: "./build"
```

Effectively the behavior would be to inline the paths from the parent config into the child config before resolving/normalizing them. I think this would lead to better decoupling. Thoughts @TwitchBronBron ?

Since this would be a breaking change it might be better to just make `stagingDir` behave the same as `rootDir` for now 🤔

**Comment by TwitchBronBron** [comment]
@josephjunker, I think I'd prefer to consistently resolve paths relative to their corresponding config location. I find that to be much easier to understand. It can become quite an import nightmare if the parent configs were inlined into children at various different nested levels. 

@bartvandenende-wm, yeah, looks like stagingDir path resolution is wrong. It should be resolved in the same way as `rootDir`
