### ISSUE TITLE
critical parsing error frequently occurs

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#120]
get a ton of these:
![image](https://user-images.githubusercontent.com/1214545/85476129-32709580-b57d-11ea-84a0-ea68c4efa62e.png)

**Comment by TwitchBronBron** [comment]
This issue is extremely difficult to reproduce within unit tests. I've tried lots of things, and am never able to reproduce. With some of the recent performance improvements, this error seems to happen much less frequently. 

I just had a conversation with @elsassph on slack about how changing 500 files all at the same time seemed to trigger this issue, so that might be a good way to try and reproduce the problem in the extension, and might give some insight on how to actually reproduce it in a spec.

**Comment by georgejecook** [comment]
no longer an issue.
