### ISSUE TITLE
Error detecting compile issue in if block

### ISSUE THREAD

**Issue by chrisdp** [rokucommunity/brighterscript#33]
The latest version of brighterscript was failing to detect the following as a compile issue:
```
if key = "back" AND then
end if
```

Here are some other examples that it also failed to detect:
```
if key = "back" OR then
end if
```
```
if key = "back" MOD then
end if
```

**Comment by TwitchBronBron** [comment]
@chrisdp can you please re-test? I think this may have gotten fixed at some point, because all of these issues are showing errors for me. 

![image](https://user-images.githubusercontent.com/2544493/79050577-e1493a80-7bf8-11ea-8126-4dbd1ae47643.png)

![image](https://user-images.githubusercontent.com/2544493/79050584-fb831880-7bf8-11ea-9497-027b1c2281b6.png)

![image](https://user-images.githubusercontent.com/2544493/79050589-06d64400-7bf9-11ea-8b57-bdfd6ea0b41e.png)

**Comment by chrisdp** [comment]
I think this is good to go. Closing issue.
