### ISSUE TITLE
PhotoTV uses BrighterScript 

### ISSUE THREAD

**Issue by andro23** [rokucommunity/brighterscript#594]
Hi,

First of all, thanks for the great project!!
I have been migrating [PhotoTV ](https://channelstore.roku.com/details/222212/phototv) to the BrighterScript language in the past few months and the code became much easier to maintain thanks to the modern syntax and features that BrighterScript bringings!

Now that you know that I am a proud user of BrighterScript, I would love PhotoTV to be listed on the project page.

Thanks,
Andro

![logo](https://user-images.githubusercontent.com/22185090/169115036-4629569c-e72e-47cc-96f7-704b570e226b.jpg)
![logo-fhd](https://user-images.githubusercontent.com/22185090/169115385-19aa1ca7-78a8-49fe-ab9f-1c5c80c52e21.jpg)

**Comment by TwitchBronBron** [comment]
I'm glad you've found value in the project. I just added the logo to the readme. Take a look and let me know if that works!

**Comment by andro23** [comment]
Looks great, thank you very much :)
Looking forward to the amazing new features!!

**Comment by andro23** [comment]
Hi @TwitchBronBron!

PhotoTV has been rebranded to Digital Picture Frame. Do you mind updating the URL to "https://digitalpictureframe.tv" and the logo to the following?

![Digital Picture Frame](https://github.com/rokucommunity/brighterscript/assets/22185090/8475283f-cf9b-4a77-980e-76e0d466f2bb)

**Comment by Christian-Holbrook** [comment]
Hi @andro23,

I opened a pull request with the changes you requested. Could you double check the image url I'm using on the PR? Comparing the new image link to previous one, I'm seeing that we are hitting `private-user-images.githubusercontent.com` instead of `user-images.githubusercontent.com`. Is there a chance you can host the image somewhere else?

[Pull Request link](https://github.com/rokucommunity/brighterscript/pull/1237/files)

**Comment by andro23** [comment]
Thank you very much @Christian-Holbrook! I uploaded the logo to S3 and updated the link to the logo on the PR.
