### ISSUE TITLE
Test assertions with Mocha/Chai produce useless output

### ISSUE THREAD

**Issue by elliot-nelson** [rokucommunity/brighterscript#710]
### ISSUE

As a developer looking to contribute to the codebase, when I run unit tests that have a failure, they often produce unhelpful / incomplete feedback.

For example:

```
Failed: Expected [ Array(3) ] to include "namespace must be declared at the root level"
```

### SUGGESTION

This is just a developer experience thing, but I'm positive Mocha can produce better results than this... where's the diff output, the list of what _was_ in the array versus what was _expected_ in the Array, etc.? (This is especially jarring coming from Jest where that stuff is "just handled".)

I'm not sure whether the fix for this is in chai, mocha, an option we can turn on/off in package.json, or something else -- just leaving it as an issue we could fix in future.

**Comment by TwitchBronBron** [comment]
It looks like chai is truncating the list if it gets too long.

This prints the way you want (because the actual items are small).
![image](https://user-images.githubusercontent.com/2544493/193612775-a3f9b256-9ef3-4c78-a296-f3a67e69ed67.png)

This is the issue you're talking about (chai truncates because the items are larger).

![image](https://user-images.githubusercontent.com/2544493/193613061-94d24309-c9ef-478d-a04d-72a8de9633d7.png)

So, to fix it, I was able configure chai to not truncate. 
![image](https://user-images.githubusercontent.com/2544493/193613751-9ff1dcac-1051-4fc8-9fb3-6225092aec2a.png)

Would you like to open a PR to adjust that setting? I think you can set it at the top of `src/testHelpers.spec.ts`, which gets imported just about everywhere.

**Comment by elliot-nelson** [comment]
What would you think about the pattern described in [this stackoverflow answer](https://stackoverflow.com/questions/57230470/setting-chai-config-globally-once-for-all-tests)?

Basically I'd make this change everywhere:

```
// before
import { expect } from 'chai';

// after
import { expect } from '../../chai-local';
```

And we could put any config options in this file.

**Comment by TwitchBronBron** [comment]
Yeah, I think that's a great option! Go with that.
