### ISSUE TITLE
inconsistent renaming of namespaced objects

### ISSUE THREAD

**Issue by ZeeD** [rokucommunity/brighterscript#817]
Note: I was looking at some way to integrate my brighterscript-based project with roca.
During some tests, I stumbled in a strange issue (that normally doesn't occur to me). To better explain my scenario, on https://github.com/ZeeD/brs_roca I've created a demo repo.

My goal is to be able to write the roca tests as `.bs`, and to be able to call the various functionalities I have developed. One example of these tests is https://github.com/ZeeD/brs_roca/blob/main/tests/foo/example.test.bs .

On https://github.com/ZeeD/brs_roca/blob/main/dist/tests/foo/example.test.brs you can see the compiled sources. While, on https://github.com/ZeeD/brs_roca/blob/main/dist/tests/foo/example.test.brs#L6 `ns.C` is correctly replaced with `ns_C`, this doesn't happen for `ns.f` and `ns.s`.

is this a problem of my configuration? a bug of the bsc compiler?

**Comment by TwitchBronBron** [comment]
The brighterscript validator and transpiler depends on scopes for namespace discovery. All files in brighterscript need to be included in a scope in order for them to function properly. Files nested under `pkg:/source` are all included automatically in the 'source' scope. Then, all other files should be explicitly included into a scope via components in some fashion. 

Namespace transpiling works by discovering a DottedGetExpression (like `ns.f`) and asking the scope if `ns` is a namespace. In this situation, your `./tests` files aren't included in any scope because it's not in the `source/` folder and it's not included by any component. BrighterScript tried to warn you about this with diagnostic code `1013` but it was disabled in the bsconfig.json

Normally I would suggest moving all these tests into the `source/` folder, but roca doesn't support that. So, with the way BrighterScript works right now, you'll need to make sure all your test files are included in at least one component. Perhaps something like this:


_components/TestComponent.xml_
```xml
<component name="TestComponent">
    <script uri="TestComponent.brs"
</component>
```

_components/TestComponent.bs_
```brighterscript
import "pkg:/tests/example.test.bs"
' you'll need to add an import line for every other *.test.bs file
```

Also, I would advise against blanket-disabling diagnostic 1002. Instead, just disable it on the `roca()` line (hopefully one way we'll support d.bs files that can declare functions like that). Like this:
```
    return roca(args).describe("ns", sub() 'bs:disable-line 1002
```

I realize this is a little counter-intuitive, but hopefully this will help get you unblocked. 

It seems to work great for me locally now:
![image](https://github.com/rokucommunity/brighterscript/assets/2544493/7e2e0eb6-0020-4ee3-9f96-07c06cabac26)

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/c5a17022-6e1f-406d-a839-f323946aca1c)

![image](https://github.com/rokucommunity/brighterscript/assets/2544493/df2af42b-fb73-4c13-bd1f-ef5a7d994346)

**Comment by TwitchBronBron** [comment]
Yeah, so you'll need to add a `'bs:disable-line` for each of those as well at the moment, unfortunately. It's a byproduct of my "component to import them all" hack. 

I'm definitely open to figuring out how to make this process easier. Just not sure quite what the right answer is.

**Comment by ZeeD** [comment]
Uhm, upon some additional testing, I think I'll abandon the usage of `roca` (and `brs`, I think).

While I acknowledge their impressive features (`brs` is basically a full brightscript interpreter!) they lack the support for some core component I need to interact with in my project...

So I think we can close this issue, as at least for me I will not need any specific feature anymore from brigherscript.
