### ISSUE TITLE
Allow specifying unchecked, build time imports

### ISSUE THREAD

**Issue by georgejecook** [rokucommunity/brighterscript#85]
many tools, such as rooibos, and many clients, and teams, produce files at build time, which are imported into components

there needs to be a way to consider that the imports for these files are valid and :
 - ignored in xml files
 - not reported as errors, in bs files, and still resolve to a <script> import tag in the corresponding xml

in maestro's compiler, I added an excluded imports array, which would check against absolute paths to imports. I guess this could be achieved by adding similar src level filters to the ignoreErrorCodes setting, as I do here; but I don't think it's really the same thing.

```    "ignoreErrorCodes": [
      1004
    ]
```

I propose something like this
```
    nonCheckedImports: [
      'source/zapp.brs',
      'source/MRuntime.brs',
      'source/rLog/rLogMixin.brs',
      'source/tests/rooibosDist.brs',
      'source/rooibosFunctionMap.brs'
    ],
    ```

with a better name; the idea being - when these imports are encountered in bs, or xml, they are preordained as safe, and have no cyclical lookups done on them

**Comment by TwitchBronBron** [comment]
I don't think this is something that BrighterScript should handle, as there are a few ways around this such as adding a stubbed out file into the project and replacing that file at runtime. 

@georgejecook are you with closing this issue?

**Comment by TwitchBronBron** [comment]
BrighterScript will always attempt to parse all script imports. At this time we don't have any plans to support ignoring certain imports. 

I think one of your primary motivations for this is that by injecting dynamic imports into the file at the top, it will cause sourcemaps to be scrambled. So, as a workaround, you can add script imports to the bottom of the file. This will most definitely cause compiler errors, but the requirement for imports to be at the top is purely a standards requirement, not a technical one. In this case, if you have some type of preprocessor, you can do the following:
1. write your "dynamic" script imports in the bottom of the file
2. above each import, add a `'bs:ignore-next-line` comment so the compiler doesn't choke on seeing imports at the bottom.
3. when the transpiler sees the imports, it will still import them and parse them. since the imports are at the bottom of the file, they will still be parsed, and we don't really care if the sourcemaps are broken at the bottom of the file because the import statements are removed at transpile time anyway.
4. your scripts will be appended to the corresponding xml files at build time.
